const ActionType = {

        /////USER AUTH
        USER_SIGNUP_REQ :  "USER_SIGNUP_REQ",
        USER_SIGNUP_SUCCESS : "USER_SIGNUP_SUCCESS",
        USER_SIGNUP_FAIL : "USER_SIGNUP_FAIL",
        USER_SIGNUP_EMPTY_MESSAGE : "USER_SIGNUP_EMPTY_MESSAGE",

        USER_LOGIN_REQ :  "USER_LOGIN_REQ",
        USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
        USER_LOGIN_FAIL : "USER_LOGIN_FAIL",
        USER_LOGIN_EMPTY_MESSAGE : "USER_LOGIN_EMPTY_MESSAGE"



}


export default ActionType